# Numpy, Pandas, Data wrangling

In [6]:
import numpy as np

In [12]:
#clkaculating variance
vac_nums = [0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,3,3,3]
a = np.array([0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,3,3,3])
mean = np.sum(a)/a.size
print(mean)

1.25


In [14]:
variance = np.sum((a - mean)**2)/a.size
print(variance)

0.9875


In [15]:
x = np.array([1, 2, 3, 4])
print(x[0]) 

1


In [18]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(x.ndim)
print(x.size)
print(x.shape) 

2
9
(3, 3)


In [19]:
x = np.array([2, 1, 3])

x = np.append(x, 4)
x = np.delete(x, 0)
x = np.sort(x)

print(x)

[1 3 4]


In [20]:
x = np.array([2, 1, 3])

x = np.append(x, 4)
x = np.sort(x)

print(x)

[1 2 3 4]


In [21]:
x = np.array([2, 1, 3])

x = np.append(x, 4)
x = np.delete(x, 2)
x = np.sort(x)

print(x)

[1 2 4]


In [22]:
data = np.array([1000, 2500, 1400, 1800, 900, 4200, 2200, 1900, 3500])
new_house = int(input())
data = np.append(data, new_house)
data = np.sort(data)
print(data)

1200
[ 900 1000 1200 1400 1800 1900 2200 2500 3500 4200]


In [24]:
x = np.arange(2, 8, 2)
x = np.append(x, x.size)
x = np.sort(x)
print(x[1])

3


In [25]:
# Creation of 1D array
arr1=np.array([10,20,30])
print("My 1D array:\n",arr1)

# My 1D array: 
# [10 20 30 40]

print("Type:", type(arr1))

My 1D array:
 [10 20 30]
Type: <class 'numpy.ndarray'>


In [26]:
# Create a sequence of integers from 0 to 20 with step of 3
arr= np.arange(0, 20, 3)
print ("A sequential array with steps of 3:\n", arr)

A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


In [32]:
z= np.array([[1,2], [3,4], [5,6]])
z = x.reshape(4)
print("Type:", type(z))

Type: <class 'numpy.ndarray'>


In [33]:
x = np.arange(1, 8, 3)
z = x.reshape(3, 1)
print(z[1][0])

4


In [34]:
x = np.array([11, 42, 8, 5, 18])
z = x[x>15]
print(z.size)

2


In [36]:
x = np.arange(3, 9)
z = x.reshape(2, 3)
print(z[1][1])

7


In [37]:
x = np.arange(1, 5)
x = x*2
print(x[:3].sum())

12
